[package]
name = "create-o3-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
crossterm = "0.26.0"
inquire = "0.5.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"

[build-dependencies]
template_builder = { path = "./template_builder" }
